# Generated by Django 4.2.6 on 2023-10-28 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppLectura', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leidos',
            name='año_publicacion',
        ),
        migrations.RemoveField(
            model_name='leyendo',
            name='año_publicacion',
        ),
        migrations.RemoveField(
            model_name='por_leer',
            name='año_publicacion',
        ),
    ]
