# Generated by Django 4.2.6 on 2023-10-30 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLectura', '0002_remove_leidos_año_publicacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leidos',
            name='año_publicacion',
            field=models.IntegerField(default=2023),
        ),
        migrations.AddField(
            model_name='leyendo',
            name='año_publicacion',
            field=models.IntegerField(default=2023),
        ),
        migrations.AddField(
            model_name='por_leer',
            name='año_publicacion',
            field=models.IntegerField(default=2023),
        ),
    ]
