# Generated by Django 4.2.6 on 2023-10-30 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLectura', '0003_leidos_año_publicacion_leyendo_año_publicacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leidos',
            name='año_publicacion',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='leyendo',
            name='año_publicacion',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='por_leer',
            name='año_publicacion',
            field=models.CharField(max_length=4),
        ),
    ]
